### DISCUSSION TITLE
Broken Link Checker - Github Action

### DISCUSSION THREAD

**Discussion by JuanPabloDiaz** [cosmoart/Freesets#23] [Ideas]
I believe that it will be a great idea to setup a GitHub action that runs periodically and checks for broken links.
 It will check all repository links once per day and create an issue in case of errors.

Github action to check for broken links in Markdown, HTML, and text files using [Lychee](https://lychee.cli.rs/), a fast link checker written in Rust.

Here is a full example of a GitHub workflow file:

It will check all repository links once per day and create an issue in case of errors.

```yaml
name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 18 * * *"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
```

I'd like to share my experience with [Lychee](https://lychee.cli.rs/). I came across it yesterday and integrated it into my project. While it was helpful in identifying some broken links, it also generated some false positives (links that appear broken but function correctly). I'm still exploring the tool's functionality to potentially fine-tune its accuracy.

On a separate note, I encountered a permissions issue when trying to open new issues.

Project implementations:

- [documentation.breadnet.co.uk](https://github.com/userbradley/documentation.breadnet.co.uk) ---> [GitHub action](https://github.com/userbradley/documentation.breadnet.co.uk/actions/runs/9006655904)
- [freeForGeeks](https://github.com/JuanPabloDiaz/freeForGeeks) ---> [GitHub action](https://github.com/JuanPabloDiaz/freeForGeeks/actions/runs/9009525313)

here is an example from my own project:
![image](https://github.com/rupali-codes/LinksHub/assets/25883220/9a469ddc-ab35-4062-a475-67ca6a3f6bce)

I hope this helps
